### ISSUE TITLE
quickstart issues

### ISSUE THREAD

**Issue by jeremiecoullon** [zombie-einstein/jaxpr-viz#9]
Hello!

I'm just trying to run the quickstart but I'm having some issues:

My setup: 
- python 3.9.16
- jax==0.4.14
- jaxlib==0.4.14
- I installed the package with: `pip install jpviz`

### scripts

I created a script with the following (from the quickstart)

```
import jax
import jax.numpy as jnp

@jax.jit
def foo(x):
    return 2 * x

@jax.jit
def bar(x):
    x = foo(x)
    return x - 1

import jpviz

jpviz.draw(bar)(jnp.arange(10))
```

But no output is created.

### jupyter notebook

I tried the same in a notebook, but following the readme I ran 

```
dot = jpviz.draw(bar, collapse_primitives=True)(jnp.arange(10))
jpviz.view_pydot(dot)
```

Here I get the error `FileNotFoundError: [Errno 2] "dot" not found in path.`

Thanks!

**Comment by zombie-einstein** [comment]
Thanks for trying it out!

> But no output is created.

Apologies this is the README being a bit unclear! `jpviz.draw(bar)(jnp.arange(10))` returns a [pydot](https://github.com/pydot/pydot) graph object which then needs to be visualised (see here https://github.com/pydot/pydot#output). So the end of the example should probably be something like

```
import jpviz

dot_graph = jpviz.draw(bar)(jnp.arange(10))
dot_graph.write_png("computation_graph.png")
```

which will render the graph and write a file. I'll extend the README to make this clearer.

> Here I get the error FileNotFoundError: [Errno 2] "dot" not found in path.

This is normally due to graphviz not being installed on your system. Though if you do, it could be something like [this](https://github.com/pydot/pydot/issues/205) issue where conda environments need a conda install of graphviz? Pydot suggests you should [usually be able to install using system package manager](https://github.com/pydot/pydot#dependencies).

**Comment by zombie-einstein** [comment]
Closing as seems the issue was the missing graphviz install

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lowlowcoder, @ygsgdbd, @tomasovic, @GaFeFi, @brianserv, @iujakchu, @inigogb, @0xdewy, @goalongway, @nickdoherty, @hqwangningbo, @rajivpo, @Jamie-Cui, @alex-fang, @vanchi198, @BaCoNL, @haua998, @p4r4no1ak, @DennisDv24, @marioabz, @elohffa, @amraymanaly, @vbrvk, @joshskeen, @bernahe, @sleepyqadir, @marioidival, @HegelXu, @omegablitz, @stechu, @wuminzhe, @mattgstevens, @lispc, @hlhdaiaaii, @jjttjj, @magj2006, @enif-lee, @gelove, @Nokhal, @caoanlong, @nkysg, @kumarishan, @iamdylanngo, @faustocarva, @nanjingboy, @edmand46, @therustmonk, @songtianyi, @wanjunling168, @p0p3yeethedevbirb, @jf-li00, @banyudu, @taqtiqa-mark, @tolgaisik, @benrod3k, @awilmoth, @bretth18, @zjb0807, @Phy-ve, @0xanonymeow, @MRGRAVITY817, @magj2006, @MaciejBaj, @wolflo, @vaad2, @icodezjb, @LooMaclin, @hlhdaiaaii, @KQisz, @sondnm, @yasindce1998, @bbenzikry, @ccamateur, @vitali2y, @minikin, @farleylai, @bernahe, @pysrbastion, @PumpkinSeed, @tututu-patch, @exdx, @kobby-pentangeli, @gerxiu, @fermuch, @prm3theus, @brianserv, @AlexiaChen, @foxytanuki, @nonsense, @jolestar, @Jzow, @Atikin-NT, @stan-dot, @skynode, @camillecorti, @dragan-novakovic, @turinglabsorg, @Caruso33, @matagus

**Comment by GitSyncPromedia** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
pulsaratmc, @0xGDSR, @scvsh, @freehere107, @blluv, @ae04071, @0x0108, @singha200, @Srinivas11789, @BoboTiG, @zah, @chichke, @SlyGuy01, @wujunze, @kkagill, @lambdamonkey, @Shodydosh, @TokenDance, @eliomain, @stephenzl, @eruma, @jinmiaoluo, @encouver, @th3093, @roma-glushko, @sid24rane, @JINGBANZ, @zippy1978, @smonami, @ToJen, @aadityapurani, @Sheys11, @iDiffract, @kissthering, @zhangzone, @andreaspz, @okdonga, @Ayushi-baghel, @wwens, @ahmet, @0xBigor, @Kitryn, @SneakFunkz, @DoubleOTheven, @nullfuzz-pentest, @sudoFerraz, @jordanlepera, @rakanuj, @DAZ85Z, @LucCADORETjnsvd, @fei4mao1, @cryptofelon, @crazelava, @FFengIll, @DukeCaesar, @zouguangxian, @0xValJohn, @fan31415, @dzmitry-lahoda, @hemanth895, @HCastano, @n0tspam, @lidatong, @br0wnD3v, @amanvir, @Namaskar-1F64F, @xhliu, @HysMagus, @Hugh-Certik, @bobobokey, @q1blue, @adityamangal1, @RHIE-coder, @chanharryhk, @dsaingre, @avalidurl, @lakai, @Cocytusi, @robriks, @puzzithinker, @MichaelGrinstead, @k-nrd, @jeffchen006, @B01AND, @sunilgitb, @chillersky, @serverlessnomad, @NFTMerchant, @yujianFresh, @johhonn, @manojpramesh, @scottrepreneur, @0xhatsune, @0xbageltoes, @zm-stack, @ProVisionDevs, @jacknewbee, @Pr3Nom, @colossus-digital
